---
title: "Yukon_plasmid_A03_A11"
author: "Jian Song"
date: "7/13/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Library A (before and plasmid) distribution by sgRNA

```{r A03}
library(ggplot2)
library(ggrepel)

myData <- read.delim(file="/Users/songj11/Desktop/Projects/Yikun_CRISPR/A01_A03.all.count.txt", header = TRUE, sep = "\t")
head(myData)
dim(myData)
# remove nonTargetingControls
myLibraryA <- myData[!grepl("NonTargetingControlGuideForHuman", myData$Gene),]
summary(myLibraryA$LCv2LA.plasmid)

# number of sgRNAs without representation
dim(myLibraryA[which(myLibraryA$LCv2LA.plasmid == 0),])[1]
noRepresentation <- myLibraryA[which(myLibraryA$LCv2LA.plasmid == 0),]
noRepresentation$Gene


# number of sgRNAs with over-representation (n > 200)
dim(myLibraryA[which(myLibraryA$LCv2LA.plasmid > 200),])[1]
overRepresentation <- myLibraryA[which(myLibraryA$LCv2LA.plasmid > 200),]
ordered <- overRepresentation[order(-overRepresentation$LCv2LA.plasmid),]
ordered$Gene

myNew <- myLibraryA[which(myLibraryA$LCv2LA.plasmid < 100),]
dim(myNew)

ggplot(myLibraryA, aes(sgRNA, LCv2LA.plasmid)) + geom_point() +
# label the genes  which high plasmid counts
geom_label_repel(data = subset(myLibraryA,  LCv2LA.plasmid>300), aes(label = Gene),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50') +
  theme_classic()

```

### 2. Library A (before and plasmid) distribution by Gene

```{r A03gene}
library(plyr)
library(magrittr)

# collapse dataframe by 'Gene' to get mean sgRNA count value for each gene
myLibraryA1 <- myLibraryA[order(myLibraryA$Gene),]
myLibraryA2 <- myLibraryA1[,c(2,3,4)]
myLibraryAByGene <- ddply(myLibraryA2,.(Gene),colwise(mean))
dim(myLibraryAByGene)
summary(myLibraryAByGene)
myLibraryAByGene$LCv2LA.before <- as.integer(myLibraryAByGene$LCv2LA.before)
myLibraryAByGene$LCv2LA.plasmid <- as.integer(myLibraryAByGene$LCv2LA.plasmid)
tail(myLibraryAByGene, 10)

# number of genes without representation ==> 0
dim(myLibraryAByGene[which(myLibraryAByGene$LCv2LA.plasmid == 0),])[1]
noRepresentationGenes <- myLibraryAByGene[which(myLibraryAByGene$LCv2LA.plasmid == 0),]
noRepresentationGenes$Gene

# number of genes with low representation ==> 0
dim(myLibraryAByGene[which(myLibraryAByGene$LCv2LA.plasmid <10),])[1]
lowRepresentationGenes <- myLibraryAByGene[which(myLibraryAByGene$LCv2LA.plasmid < 10),]
lowRepresentationGenes$Gene

# number of genes with over-representation (n > 200) ==> 13
dim(myLibraryAByGene[which(myLibraryAByGene$LCv2LA.plasmid > 200),])[1]
overRepresentationGenes <- myLibraryAByGene[which(myLibraryAByGene$LCv2LA.plasmid > 200),]
orderedGenes <- overRepresentationGenes[order(-overRepresentationGenes$LCv2LA.plasmid),]
orderedGenes$Gene

myNewGenes <- myLibraryAByGene[which(myLibraryAByGene$LCv2LA.plasmid < 100),]
dim(myNewGenes)

ggplot(myLibraryAByGene, aes(Gene, LCv2LA.plasmid)) + geom_point() +
# label the genes which high plasmid counts
geom_label_repel(data = subset(myLibraryAByGene,  LCv2LA.plasmid>300), aes(label = Gene),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50') +
  theme_classic()
```

